camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  #eventing:
  #  execution: true

loan.broker:
  credit.url:
    host: localhost
    port: 8080
